### ISSUE TITLE
Refactor zero2ckb training course

### ISSUE THREAD

**Issue by Flouse** [Flouse/ckb-academy#3]
## zero2ckb designed by @retricsu
- https://zero2ckb.ckbapp.dev
- https://github.com/RetricSu/zero2ckb-web

## TODO
- [x] Based on CKB Testnet public RPC - https://testnet.ckb.dev/rpc
  - Problem statement：
    - zero2ckb-server was based on a self-built CKB devnet, which lacks maintenance and has occasional failures
    - failed to keep up with the latest version of CKB in time
    - inconvenient to query the transaction created by developers
  - Tasks:
    - [x] Interact with CKB testnet to make things easier and clearer
    - [ ] (optional) guide the new developer how to read transaction on [ckb-explorer](https://pudge.explorer.nervos.org/)
  
- [x] Connect a wallet and use omni_lock to sign transactions in the exercises
  - Problem statement：
     https://zero2ckb.ckbapp.dev/learn#hands-on → 3 wallets were provided.
     But when multiple users practice online at the same time, it is difficult to avoid conflicts.
  - Tasks
    - [x] Use Popular browser wallet extensions such as [Metamask](https://metamask.io/) or [Brave wallet](https://brave.com/wallet/), it may provide a better experience when a developer want to sign transactions
    - [x] Auto Faucet
      When a new developer arrives [zero2ckb.ckbapp.dev/learn](http://zero2ckb.ckbapp.dev/learn) and connects to a wallet, the server will send 10 * 100 CKB cells to his/her address for later practice

- [ ] Refactor UI/UX
   - [x] fix: the current zero2ckb page cost too much CPU
   - [x] Make the error prompts in the exercises more friendly
   - [x] Design check steps components for zero2ckb
   - etc.

## Reference
- https://blog.cryptape.com/construct-and-send-your-first-ckb-transaction
